server {
    listen 80;
    server_name employee.local.lab;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name employee.local.lab;

    ssl_certificate /etc/nginx/ssl/employee.crt;
    ssl_certificate_key /etc/nginx/ssl/employee.key;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
    }
}