pipeline {
    agent any

    environment {
        DOCKER_USERNAME = "kejawa"
        COMPOSE_FILE = "docker-compose.prod.yml"
    }

    stages {
        stage('Checkout Repository') {
            steps {
                checkout scm
            }
        }

        stage('Verify Docker Installation') {
            steps {
                sh 'docker --version'
                sh 'docker compose version'
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login \
                    -u "$DOCKER_USER" \
                    --password-stdin
                    '''
                }
            }
        }

        stage('Pull Latest Images') {
            steps {
                sh "docker compose -f ${COMPOSE_FILE} pull"
            }
        }

        stage('Stop Existing Containers') {
            steps {
                sh "docker compose -f ${COMPOSE_FILE} down"
            }
        }

        stage('Deploy New Containers') {
            steps {
                sh """
                    cd ~/employee-directory
                    docker compose -f ${COMPOSE_FILE} up -d
                   """ 
            }
        }

        stage('Verify Running Containers') {
            steps {
                sh 'docker ps'
            }
        }

        stage('Health Check') {
            steps {
                sh 'curl --fail http://localhost:3000/health'
            }
        }
    }

    post {
        success {
            echo "Deployment Successful"
        }
        failure {
            echo "Deployment Failed"
        }
        always {
            sh 'docker image prune -f'
        }
    }
}